from playwright.sync_api import sync_playwright
from e2e_env import OUT, BASE
ok=[0,0]
def chk(n,c,x=''):
    ok[0 if c else 1]+=1; print('PASS' if c else 'FAIL',n,x)
def ev(pg,js): return pg.evaluate(js)
def slot(pg): return ev(pg,"(()=>{const e=document.getElementById('rm-alert-slot');return e?{cls:e.className,label:e.querySelector('.ea-label').textContent,val:e.querySelector('.ea-value').textContent,more:(e.querySelector('.rm-alert-more')||{}).textContent||''}:null})()")
def feedn(pg): return ev(pg,"document.querySelectorAll('#race-engineer-feed .engineer-alert').length")
def page(pw,vw=1600,vh=900):
    b=pw.chromium.launch(args=['--no-sandbox']); ctx=b.new_context(viewport={'width':vw,'height':vh}); pg=ctx.new_page(); errs=[]
    pg.on('pageerror',lambda e:errs.append(str(e)))
    pg.route('**/api/**',lambda r:r.fulfill(status=404,body='{}'))
    pg.goto(BASE+'/'); pg.wait_for_timeout(1500); return b,ctx,pg,errs
with sync_playwright() as pw:
    b,ctx,pg,errs=page(pw)
    # ---- T8 ----
    ev(pg,"rmRaiseAlert('FUEL RATE','2.10 L/lap','notice')"); s=slot(pg)
    chk('notice 1件: 枠に表示',s and s['label']=='FUEL RATE' and 'notice' in s['cls'] and s['more']=='',s)
    ev(pg,"rmRaiseAlert('LAP ANOMALY','L4 +12%','warning')"); s=slot(pg)
    chk('warning が notice より優先',s['label']=='LAP ANOMALY' and s['more']=='+1',s)
    ev(pg,"rmRaiseAlert('OIL PRESSURE','1.8 bar','serious')"); s=slot(pg)
    chk('serious が最優先・他の件数+2',s['label']=='OIL PRESSURE' and 'serious' in s['cls'] and s['more']=='+2',s)
    chk('枠は1つだけ・トーストは増えない',feedn(pg)==1 and ev(pg,"document.querySelectorAll('.rm-alert-slot').length")==1)
    ev(pg,"document.getElementById('rm-alert-slot').click()"); s=slot(pg)
    chk('確認で消去→次に重要な warning',s['label']=='LAP ANOMALY' and s['more']=='+1',s)
    ev(pg,"document.getElementById('rm-alert-slot').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))"); s=slot(pg)
    chk('Enter でも確認できる→notice',s['label']=='FUEL RATE',s)
    ev(pg,"document.getElementById('rm-alert-slot').click()")
    chk('全て確認すると枠が消える',slot(pg) is None and feedn(pg)==0)
    ev(pg,"rmRaiseAlert('TYRE TEMP','FL +18°C/5s','warning');rmRaiseAlert('TYRE TEMP','FR +20°C/5s','warning')"); s=slot(pg)
    chk('同じラベルは新しい方で置換(件数+なし)',s['val'].startswith('FR') and s['more']=='',s)
    ev(pg,"rmState.alerts.active=[]; rmRenderAlerts()")
    # 期限
    ev(pg,"rmRaiseAlert('FUEL RATE','x','notice');rmRaiseAlert('LAP ANOMALY','y','warning');rmRaiseAlert('OIL PRESSURE','z','serious');rmState.alerts.active.forEach(a=>a.at-=61000);rmRenderAlerts()")
    s=slot(pg); chk('61秒後: notice/warning は消え serious は残る',s and s['label']=='OIL PRESSURE' and s['more']=='',s)
    ev(pg,"rmState.alerts.active.forEach(a=>a.at-=5*60*1000);rmRenderAlerts()")
    chk('serious も5分で消える',slot(pg) is None)
    # 実際の検出経路(油圧の急低下 → rmOutlierTick)
    ev(pg,"""(()=>{let el=document.getElementById('oil-pressure'); for(let i=0;i<5;i++){el.textContent='5.0'; rmOutlierTick();} el.textContent='2.0'; rmOutlierTick();})()""")
    s=slot(pg); chk('検出経路: 油圧低下が枠に serious で出る',s and s['label']=='OIL PRESSURE' and 'serious' in s['cls'],s)
    ev(pg,"rmState.alerts.active=[]; rmRenderAlerts()")
    ev(pg,"ensureAnalysisInit()")
    # DRIVE / REVIEW は従来どおりトースト
    ev(pg,"document.body.classList.add('drive-mode'); rmRaiseAlert('OIL PRESSURE','1.0 bar','serious')")
    chk('DRIVE: 枠を使わず従来のトースト',slot(pg) is None and feedn(pg)==1 and ev(pg,"document.querySelector('#race-engineer-feed .engineer-alert').classList.contains('rm-alert-slot')")==False)
    ev(pg,"document.body.classList.remove('drive-mode'); document.body.classList.add('review-mode'); rmRaiseAlert('LAP ANOMALY','L1','warning')")
    chk('REVIEW: 枠を使わずトースト',slot(pg) is None and feedn(pg)==2)
    ev(pg,"document.body.classList.remove('review-mode')")
    # ---- T9 ----
    put=lambda t,pl: ev(pg,f"(()=>{{const i=document.getElementById('fuel-target-input'); i.value='{t}'; i.dispatchEvent(new Event('input',{{bubbles:true}})); document.getElementById('fuel-per-lap').textContent='{pl}'; rmFuelTargetTick(); const o=document.getElementById('fuel-target-diff'); return [o.textContent,o.className];}})()")
    ev(pg,"rmInitFuelTarget()")
    r=put('5.00','5.30'); chk('使い過ぎ: +0.30 で over',r[0]=='+0.30 L/lap' and 'over' in r[1],r)
    r=put('5.00','4.70'); chk('節約: -0.30 で under',r[0]=='-0.30 L/lap' and 'under' in r[1],r)
    r=put('5.00','5.05'); chk('±2%以内は on(目標どおり)',r[0]=='+0.05 L/lap' and 'on' in r[1] and 'over' not in r[1],r)
    r=put('5.00','--'); chk('PER LAP 未確定は --',r[0]=='--',r)
    r=put('','5.30'); chk('目標未設定は --',r[0]=='--',r)
    r=put('-1','5.30'); chk('負の目標は無効(--)',r[0]=='--',r)
    put('4.50','4.90')
    chk('目標が localStorage に保存される',ev(pg,"localStorage.getItem('gt7.fuelTargetPerLap')")=='4.5',ev(pg,"localStorage.getItem('gt7.fuelTargetPerLap')"))
    pg.reload(); pg.wait_for_timeout(2500)
    chk('再読み込みで目標が復元される',ev(pg,"document.getElementById('fuel-target-input').value")=='4.5',ev(pg,"document.getElementById('fuel-target-input').value"))
    ev(pg,"document.getElementById('fuel-per-lap').textContent='4.90'"); pg.wait_for_timeout(1500)
    chk('復元後、1Hzで差分が自動更新される',ev(pg,"document.getElementById('fuel-target-diff').textContent")=='+0.40 L/lap',ev(pg,"document.getElementById('fuel-target-diff').textContent"))
    chk('pageerror 0',not errs,errs); b.close()
    for vw,vh in ((390,844),(1920,1080)):
        b,ctx,pg,errs=page(pw,vw,vh)
        ev(pg,"rmRaiseAlert('OIL PRESSURE','1.8 bar','serious');rmRaiseAlert('LAP ANOMALY','L4 +12%','warning')")
        ev(pg,"(()=>{const i=document.getElementById('fuel-target-input'); i.value='4.5'; i.dispatchEvent(new Event('input',{bubbles:true})); document.getElementById('fuel-per-lap').textContent='4.90'; rmFuelTargetTick();})()")
        pg.wait_for_timeout(500)
        sw=ev(pg,"[document.documentElement.scrollWidth,innerWidth]"); chk(f'{vw}px: 横スクロールなし',sw[0]<=sw[1],sw)
        r=ev(pg,"(()=>{const r=document.querySelector('.fuel-target-row').getBoundingClientRect(),c=document.querySelector('.fuel-card').getBoundingClientRect();return [Math.round(r.right),Math.round(c.right)]})()")
        chk(f'{vw}px: 目標行がカード内に収まる',r[0]<=r[1]+1,r)
        pg.screenshot(path=f'{OUT}/t555a_{vw}.png'); chk(f'{vw}px: pageerror 0',not errs,errs); b.close()
print('PASS',ok[0],'FAIL',ok[1])
